### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by v6r** [Social404/Discord-Account-Token-Generator-#1]
D:\Downloads\Discord-Account-Token-Generator--main>node index
======
(node:16688) UnhandledPromiseRejectionWarning: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (884014).
    at ChromeLauncher.launch (D:\Downloads\Discord-Account-Token-Generator--main\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:82:27)
    at PuppeteerNode.launch (D:\Downloads\Discord-Account-Token-Generator--main\node_modules\puppeteer\lib\cjs\puppeteer\node\Puppeteer.js:125:31)
    at PuppeteerExtra.launch (D:\Downloads\Discord-Account-Token-Generator--main\node_modules\puppeteer-extra\dist\index.cjs.js:129:41)
    at async D:\Downloads\Discord-Account-Token-Generator--main\index.js:225:21
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Rund setup.bat, installed manually in cmd, and opened start.bat

**Comment by Azorixxx** [comment]
Just download chromium version: 884014

**Comment by v6r** [comment]
i downloadet but nothing changed. still same error
